// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdyobjigbabxvilkngnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkeW9iamlnYmFieHZpbGtuZ250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTUxMDcsImV4cCI6MjA3MjA5MTEwN30.-RwRn2wbfPVn4WH3wLpB_cF9R_0i4QAKO1SJ-md_mKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});